### ISSUE TITLE
WhenActive causes unexpected command scheduling

### ISSUE THREAD

**Issue by Rodney-Lewis** [FRC-1250/Team-1250-InfiniteRecharge2020#12]
https://github.com/FRC-1250/Team-1250-InfiniteRecharge2020/blob/49f683b51f87b84482aa3d92c905129dec45f9d7/src/main/java/frc/robot/utilities/StateTrigger.java#L38-L41

WhenActive triggers a command to start. However, there are some command that are configured to be non interrupted AND do not have a end condition. For example, spin thrice.

https://github.com/FRC-1250/Team-1250-InfiniteRecharge2020/blob/49f683b51f87b84482aa3d92c905129dec45f9d7/src/main/java/frc/robot/RobotContainer.java#L205

https://github.com/FRC-1250/Team-1250-InfiniteRecharge2020/blob/errorsWithState/src/main/java/frc/robot/commands/panel/Cmd_SpinThrice.java

So we trigger a blocking command for the panel group that will never end nor can be canceled! 

I suggest changing the statetrigger to use whileActiveOnce

public void whileActiveOnce(Command cmd, boolean interruptible) {
        trigger.whileActiveOnce(cmd, interruptible);
    }

Description from the trigger.java...
 * Starts the given command when the trigger initially becomes active, and ends it when it becomes
   * inactive, but does not re-start it in-between.

By doing this we force button holding for a particular action OR we need to ensure all commands can be interrupted and be done so in a safe manor OR need to have a timeout if they're blocking.

**Comment by Rodney-Lewis** [comment]
https://github.com/FRC-1250/Team-1250-InfiniteRecharge2020/blob/a13f7c9e1d5017256be97d9ebc47229311413881/src/main/java/frc/robot/state/Sub_StateManager.java#L26

Not sure how this wasn't being set by the command? It's what populated shuffleboard so you would see it there as well. Simulating the same code seems to be fine upon state change in shuffleboard.

**Comment by eusmanova** [comment]
changed to whileActiveOnce in StateTrigger. i don't know how you're doing it differently, but i don't get anything for the state changes on shuffleboard (blank under Robot Mode) nor in the print statements, not even in your original StateManager branch. i tried on both tars and my pc, but no change. i'll try tomorrow on the actual robot

**Comment by Rodney-Lewis** [comment]
If it's empty, then it sounds like the robot isn't "enabled". If you're using the simulator you have to enable the robot via the GUI.

**Comment by eusmanova** [comment]
that was indeed the reason

**Comment by Rodney-Lewis** [comment]
Thank you for contacting tech support!
