### ISSUE TITLE
Move LED logic to Sub_utility

### ISSUE THREAD

**Issue by Rodney-Lewis** [FRC-1250/Team-1250-InfiniteRecharge2020#3]
https://github.com/FRC-1250/Team-1250-InfiniteRecharge2020/blob/23bb2e29faf455437f52855c6850ee96e8774e55/src/main/java/frc/robot/Robot.java#L46-L56

https://github.com/FRC-1250/Team-1250-InfiniteRecharge2020/blob/23bb2e29faf455437f52855c6850ee96e8774e55/src/main/java/frc/robot/Robot.java#L73-L82

**Comment by Rodney-Lewis** [comment]
Doesn't necessarily need to be sub_utility but if we're going to use it, we should probably move this from Robot.java as no other logic really exists there.

**Comment by FRC-1250** [comment]
most logic moved to s_util in latest errorsWithState commit
